### ISSUE TITLE
Probeer geen spaties te gebruiken in bestandsnamen

### ISSUE THREAD

**Issue by rutgerkock** [Mossati/the-startup-responsive-interactieve-website#11]
Je hebt in al je bestanden een spatie staan, probeer dit te vermijden, volgens google kan dit errors veroorzaken bij het verzetten van bestanden.
https://github.com/Mossati/the-startup-responsive-interactieve-website/blob/8269f5f7b6608eb7816bce227263a1d6b1d91cd2/index.html#L69

**Comment by Mossati** [comment]
namen zijn veranderd naar "image-3"
